# Generated by Django 3.1.4 on 2020-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201207_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='time_r',
            field=models.DateField(),
        ),
    ]
